import { createClient } from "@/lib/supabase/server"
import { NextResponse } from "next/server"
const PDFDocument = require("pdfkit/js/pdfkit.standalone");
import { z } from "zod"

const pdfSchema = z.object({
    jobId: z.string().uuid(),
})

export async function POST(request: Request) {
    try {
        const body = await request.json()
        const { jobId } = pdfSchema.parse(body)
        const supabase = await createClient()

        // 1. Get Job
        const { data: job, error } = await supabase
            .from("jobs")
            .select("*")
            .eq("id", jobId)
            .single()

        if (error || !job) {
            return NextResponse.json({ error: "Job not found" }, { status: 404 })
        }

        if (!job.expressions_urls || !Array.isArray(job.expressions_urls)) {
            return NextResponse.json({ error: "No expressions found" }, { status: 400 })
        }

        console.log(`Generating PDF for Job ${jobId} with ${job.expressions_urls.length} images...`);

        // 2. Create PDF Stream
        const doc = new PDFDocument({ autoFirstPage: false })
        const buffers: Buffer[] = []

        doc.on('data', buffers.push.bind(buffers))

        const pdfPromise = new Promise<Buffer>((resolve, reject) => {
            doc.on('end', () => {
                const pdfData = Buffer.concat(buffers)
                resolve(pdfData)
            })
            doc.on('error', reject)
        })

        // 3. Add Images to PDF
        // Helper to fetch image buffer
        const fetchImage = async (url: string) => {
            const res = await fetch(url);
            if (!res.ok) throw new Error(`Failed to fetch image: ${url}`);
            return Buffer.from(await res.arrayBuffer());
        }

        for (const item of job.expressions_urls) {
            try {
                if (!item.url || !item.url.startsWith('http')) continue;

                const imgBuffer = await fetchImage(item.url);

                doc.addPage({ size: [600, 800], margin: 50 });

                // Add Title
                doc.fontSize(24).text(item.expression, { align: 'center' });
                doc.moveDown();

                // Add Image (Fit to page width)
                // Convert buffer to Uint8Array for standalone PDFKit compatibility
                const imgArrayBuffer = new Uint8Array(imgBuffer);

                doc.image(imgArrayBuffer, {
                    fit: [500, 600],
                    align: 'center',
                    valign: 'center'
                });

                // Add Footer
                doc.fontSize(10).text("Generated by Expressr.ai", 50, 750, { align: 'center', color: 'grey' });

            } catch (err) {
                console.error(`Skipping image ${item.expression}:`, err);
            }
        }

        doc.end();

        const pdfBuffer = await pdfPromise;

        // 4. Upload PDF to Supabase
        const filename = `${jobId}/expressr-pack.pdf`;
        const { error: uploadError } = await supabase.storage
            .from('generated-images') // Reusing the same public bucket
            .upload(filename, pdfBuffer, {
                contentType: 'application/pdf',
                upsert: true
            });

        if (uploadError) {
            console.error("PDF Upload failed:", uploadError);
            throw uploadError;
        }

        const { data: publicUrlData } = supabase.storage
            .from('generated-images')
            .getPublicUrl(filename);

        const pdfUrl = publicUrlData.publicUrl;
        console.log(`PDF Uploaded: ${pdfUrl}`);

        // 5. Update Job
        const { error: dbError } = await supabase
            .from("jobs")
            .update({
                pdf_url: pdfUrl
            })
            .eq("id", jobId)

        if (dbError) {
            console.error("Database update failed:", dbError);
        } else {
            console.log("Database updated with PDF URL");
        }

        // 6. Send Email (Optional - can be done by looking up user email)
        // ...

        return NextResponse.json({ success: true, pdfUrl })

    } catch (error) {
        console.error("PDF generation failed:", error)
        return NextResponse.json({ error: "PDF generation failed" }, { status: 500 })
    }
}
