
import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import PDFDocument from "pdfkit";

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

export async function GET(request: Request) {
    try {
        const { searchParams } = new URL(request.url);
        const jobId = searchParams.get("job_id");

        if (!jobId) {
            return NextResponse.json({ error: "Job ID required" }, { status: 400 });
        }

        const { data: job } = await supabase
            .from("jobs")
            .select("*")
            .eq("id", jobId)
            .single();

        if (!job) {
            return NextResponse.json({ error: "Job not found" }, { status: 404 });
        }

        // Gate access: Must be paid or complete (if free tier logic changes, but currently PDF is premium)
        if (!job.is_paid) {
            return NextResponse.json({ error: "Unlock full pack to download PDF" }, { status: 403 });
        }

        // Create PDF
        const doc = new PDFDocument({ autoFirstPage: false });

        // Stream response
        const headers = new Headers();
        headers.append("Content-Disposition", `attachment; filename="expressr-pack.pdf"`);
        headers.append("Content-Type", "application/pdf");

        const stream = new ReadableStream({
            async start(controller) {
                doc.on("data", (chunk) => controller.enqueue(chunk));
                doc.on("end", () => controller.close());

                // Cover Page
                doc.addPage();
                doc.fontSize(30).text("My AI Expressions", { align: "center" });
                doc.moveDown();
                doc.fontSize(15).text("Generated by Expressr.ai", { align: "center" });
                doc.moveDown();

                // Add Images
                if (job.images) {
                    for (const img of job.images) {
                        try {
                            const imgRes = await fetch(img.url);
                            const imgBuffer = Buffer.from(await imgRes.arrayBuffer());

                            doc.addPage();
                            // Fit image to page
                            doc.image(imgBuffer, {
                                fit: [450, 450],
                                align: 'center',
                                valign: 'center'
                            } as any); // cast to any to avoid strict type checks if types are outdated
                            doc.fontSize(12).text(img.expression.toUpperCase(), 100, 500, { align: "center", width: 400 });
                        } catch (e) {
                            console.error(`Failed to load image ${img.expression}`, e);
                        }
                    }
                }

                doc.end();
            }
        });

        return new NextResponse(stream, { headers });

    } catch (error: any) {
        console.error("PDF generation failed:", error);
        return NextResponse.json({ error: "PDF generation failed" }, { status: 500 });
    }
}
